<div class="row">
	<div class="col-md-3">
        <?php echo $this->PageNav(); ?>
    </div>
	<div class="col-md-9">
	    <h3>Page Details</h3>
		<div class="row">
		  <div class="col-md-2 text-primary"><b>Route</b></div>
		  <div class="col-md-10"><?php echo $this->escape($this->page->route); ?></div>
		</div>
		<div class="row">
		  <div class="col-md-2 text-primary"><b>Module</b></div>
		  <div class="col-md-10"><?php echo $this->escape($this->page->module); ?></div>
		</div>
		<div class="row">
		  <div class="col-md-2 text-primary"><b>Controller</b></div>
		  <div class="col-md-10"><?php echo $this->escape($this->page->controller); ?></div>
		</div>
		<div class="row">
		  <div class="col-md-2 text-primary"><b>Action</b></div>
		  <div class="col-md-10"><?php echo $this->escape($this->page->action); ?></div>
		</div>
		<div class="row">
		  <div class="col-md-2 text-primary"><b>Access</b></div>
		  <div class="col-md-10"><?php echo $this->escape($this->page->acl_resource_display); ?></div>
		</div>
		<div class="row">
		  <div class="col-md-12 text-right">
		      <a href="<?php echo $this->url(
		              array('module' => 'page', 
                            'controller' => 'update', 
                            'action' => 'page', 
                            'page_id' => $this->escape($this->page->page_id)) ); ?>" 
                type="button" class="btn btn-warning" data-toggle="tooltip" 
                data-placement="top" title="Update Page"><i class="glyphicon glyphicon-pencil"></i></a>
              <a href="<?php echo $this->url( array('module' => 'page',
                    'controller' => 'delete', 'action' => 'page', 'page_id' => $this->escape($this->page->page_id)) ); ?>" type="button" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Delete Page"><i class="glyphicon glyphicon-remove"></i></a>
                           
		  </div>
		</div>
		<hr />
		<h3>Meta Translations</h3>
		<table class="table table-striped table-bordered table-responsive">
			<thead>
				<tr>
				    <th class="col-md-2">Language</th>
				    <th>Page Title</th>
				    <th class="col-md-2"></th>
				</tr>
		    </thead>
		    <tbody>
		    <?php foreach($this->metas as $meta):?>
		    <tr>
		      <td><a href="<?php echo $this->url( array(
		              'module' => 'page',
		              'controller' => 'view',
		              'action' => 'meta',
		              'page_meta_id' => $this->escape($meta->page_meta_id) ) ); ?>">
		              <?php echo $this->escape($meta->language); ?>
		          </a>
		      </td>
		      <td><?php echo $this->escape($meta->page_title); ?></td>
		      <td class="text-right">
		          <a href="<?php echo $this->url(
		              array('module' => 'page', 
                            'controller' => 'update', 
                            'action' => 'meta', 
                            'page_meta_id' => $this->escape($meta->page_meta_id)) ); ?>" 
                             type="button" class="btn btn-warning" data-toggle="tooltip" 
                             data-placement="top" 
                             title="Update Page Translation">
                             <i class="glyphicon glyphicon-pencil"></i>
                   </a>
                   <a href="<?php echo $this->url( 
                           array('module' => 'page',
                               'controller' => 'delete', 
                               'action' => 'meta', 
                               'page_meta_id' => $this->escape($meta->page_meta_id)) ); ?>" 
                               type="button" class="btn btn-danger" 
                               data-toggle="tooltip" 
                               data-placement="top" 
                               title="Delete Page Translation">
                               <i class="glyphicon glyphicon-remove"></i>
                   </a>
                        
		      </td>
		    </tr>
		    <?php endforeach;?>
		    </tbody>
		</table>
	</div>
</div>