
<script src="/dist/js/helper.js" type="text/javascript"></script>
<script type="text/javascript">

$("document").ready(function ( ) {
	$("#alertSuccesBox").hide();
	$("#alertErrorCommentBox").hide();
    getData(); 
    getComments();
});


// loads well data
function getData() {
	$.ajax({
	    url : "/well/json/view/id/<?php echo $this->id; ?>",
	    type: "GET",
	    dataType: "json",
	    success: successFn,
	    error: errorFn,
	    complete: function (xhr, status) {
		}
	});
}


//get comments
function getComments() {		
		$.ajax({
		    url : "/well/json/get-comments/id/<?php echo $this->id; ?>",
		    type: "GET",
		    dataType: "json",
		    success: commentsSuccess,
		    error: errorFn,
		    complete: function (xhr, status) {
		        
			}
		});
}

// load comments into box
function commentsSuccess(result) {
	if(result.code == 200) {
		 var count = 0;
		 var d = result.response;		
		 $.each(d,  function( index, value ) {
			 
			  var html = '<div class="row">';
			  html = html + '<div class="col-md-12"><span class="text-primary">Comment by '+value.name+' <small>on '+value.well_comment_created+'</small></span>';
			  if(value.user_id == <?php echo $this->getIdentity()->auth_id; ?>) {
				   html = html + '<div class="pull-right"><button class="btn btn-primary btn-sm" data-comment-id="'+value.id+'" onCLick="editComment('+value.id+')">Edit</button> <button id="deleteCommentBtn" class="btn btn-danger btn-sm" onClick="deleteComment('+value.id+')">Delete</button></div></div></div>';
			  }
			  html = html +'<div class="row"><div class="col-md-2"><div class="thumbnail"><img src="/images/default-avatar.png" alt="" class="img-responsive img-rounded"></div></div>';
			  html = html +'<div class="col-md-10"><p class="commentTxt">'+value.well_comment_txt+'</p></div</div></div>';
			  html = html + '<div class="row"><div class="col-md-12"><hr /></div></div>';
			  $("#commentBox").append(html);	
			  				  
		     count++;
		 });
		 if(count == 0 ) {
			 $("#commentBox").append('<div class="alert alert-warning">There are no recorded comments for this well</div>');
		 }
	} else {
		$("#alertError").html(result.response);
	    $("#alertError").show();
	}
}

// edit comment form
function editComment(commentId) {var resource = "#commentTxt_"+commentId;
    $("#editCommentAlert").hide();
    $("#editCommentSuccess").hide();
    $.ajax({
	    url : "/well/json/get-comment/id/" + commentId,
	    type: "GET",
	    dataType: "json",
	    success: function (result) {
	        console.log(result);		    
	    	$("#editComment").modal('show');
	    	$("#commentEditTextFld").val(result.response.well_comment_txt);
	    },
	    error: errorFn,
	    complete: function (xhr, status) {
	         
		}
	});

    $("#doEditCommentBtn").click(function () {
    	wellCommentTxt = $("#commentEditTextFld").val();
    	$.ajax({
	        type: "POST",
	        url: "/well/json/update-comment",
	        success: function(result) { 
	            if (result.code == 200) { 
	            	$("#editCommentSuccess").html('Your Comment was updated');
	    	    	$("#editCommentSuccess").show();
	    	    	$("#editCommentFormGroup").hide();
	    	    	$("#doEditCommentBtn").hide();
	    	    	$('#editComment').on('hidden.bs.modal', function (e) {
	    	    		location.reload();
	    	        })
	    	    } else {
	                $("#editCommentAlert").html(result.response);
	        	    $("#editCommentAlert").show();
	            }
	        },
	        error: function (xhr, ajaxOptions, thrownError) {            
	            console.log(thrownError);
	        },
	        data: {id: commentId, wellCommentTxt: wellCommentTxt},
	        dataType: 'json',
	    });
    });
}

// delete comment confirm
function deleteComment(commentId) {
	$("#deleteCommentAlert").hide();
	$("#deleteCommentSuccess").hide();
	$.ajax({
	    url : "/well/json/get-comment/id/" + commentId,
	    type: "GET",
	    dataType: "json",
	    success: function (result) {		    
	        $("#deleteComment").modal('show');
	    	$("#deleteCommentTxt").html(result.response.well_comment_txt);
	    },
	    error: errorFn,
	    complete: function (xhr, status) {
	         
		}
	});	

	// do delete
	$("#doDeleteCommentBtn").click(function () {
		 $.ajax({
		        type: "POST",
		        url: "/well/json/delete-comment",
		        success: function(result) { 
		            if (result.code == 200) { 
		    	    	$("#deleteCommentSuccess").html('Your Comment was deleted');
		    	    	$("#deleteCommentSuccess").show();
		    	    	$("#doDeleteCommentBtn").hide();
		    	    	$("#deleteCommentInfo").hide();
		    	    	$('#deleteComment').on('hidden.bs.modal', function (e) {
		    	    		location.reload();
		    	        })
		    	    } else {
		                $("#deleteCommentAlert").html(result.response);
		        	    $("#deleteCommentAlert").show();
		            }
		        },
		        error: function (xhr, ajaxOptions, thrownError) {            
		            console.log(thrownError);
		           
		        },
		        data: {id: commentId},
		        dataType: 'json',
		 });		 
	})
	
}


// return well results
function successFn (result) {
	if(result.code == 200) {
	    var d = result.response;    
	    $("#wlCountyCode").html(getCounty(d.wl_county_code));
	    $("#state").html(d.state);
	    $("#wellStreet").html(d.street_of_well);
	    $("#wellCity").html(d.city_of_well);
	    $("#wlNbr").html(d.wl_nbr);
	    $("#wellTagNbr").html(d.well_tag_nbr);
	    $("#txLot").html(d.tax_lot);
	    $("#startcardNbr").html(d.startcard_nbr);
	    $("#typeOfLog").html(getLogType(d.type_of_log));
	    
	    var trs = d.township + " " + d.township_char + " " + d.t_range + " " + d.range_char + " " + d.sctn + " ";
	    if(d.qtr160 != 0) {
	    	trs = trs + d.qtr160;
	    }

	    if(d.qtr40 != 0) {
	    	trs = trs + d.qtr40;
	    }
	    $("#trs").html(trs);
	    $("#latLng").html(d.latitude + "/" + d.longitude);
	    $("#name").html(d.name_first + " " + d.name_last);
	    $("#nameCompany").html(d.name_company);
	    $("#address").html(d.street + " " + d.city + ", " + d.state + " " + d.zip );
	    $("#startDate").html(d.start_date);
	    $("#completeDate").html(d.complete_date);
	    $("#receivedDate").html(d.received_date);
	    $("#depthFirstWater").html(d.depth_first_water + ' <small class="text-muted">ft</small>');
	    $("#depthDrilled").html(d.depth_drilled + ' <small class="text-muted">ft</small>');
	    $("#completedDepth").html(d.completed_depth + ' <small class="text-muted">ft</small>');
	    $("#postStaticWaterLevel").html(d.post_static_water_level + ' <small class="text-muted">ft</small>');
	    $("#maxYield").html(d.max_yield + ' <small class="text-muted">gpm</small>');
	    $("#lastWork").html(getWork(d));
	    $("#use").html(getUse(d));	    
	    $("#driller").html('<a href="#" id="showDriller" data-toggle="modal" data-target="#viewDriller">' + d.bonded_name_first + ' ' + d.bonded_name_last + '</a>');
	    $("#drillerName").html(d.bonded_name_first + ' ' + d.bonded_name_last);
	    $("#bondedLicenseNbr").html(d.bonded_license_nbr);
	    if(d.bonded_license_nbr < 1) {
	        $("#viewDrillerBtn").attr("disabled", "disabled");
	    }	    	
	    $('#mapContainer').gmap({'zoom': 16, 'center': d.latitude+","+d.longitude}).bind('init', function(ev, map) {
	    	$('#mapContainer').gmap('addMarker', {'position': d.latitude + ',' +d.longitude, 'bounds': false});
	    });
	    	   
	    $("#stateReportBtn").attr("href", "http://apps.wrd.state.or.us/apps/misc/vault/vault.aspx?wl_county_code="+d.wl_county_code+"&wl_nbr=" + d.wl_nbr);


	    
	    // click handlers
	    $( "#favoritesBtn" ).click(function() {
	    	$('#addFavorites').modal('hide');
	    	$("#alertSuccessBoxTxt").html(d.street + ' ' + d.city + 'was added to your favorites. <i class="fa fa-star-o fa-fw"></i>');
	    	$("#alertSuccesBox").show();
	    	$("#addToFavortiesBtn").prop("disabled",true);

	    	// save fav
	    });

	    
	    // save comment
	    $("#saveCommentBtn").click(function () {
	    	var commentTxt = $("#commentTextFld").val();
	    	if($("#commentPrivateChk").is(':checked')) {
		    	var commentPrivate = 1;
	    	} else {
	    		var commentPrivate = 0;
	    	}
	    	var result = "";
	    	 $.ajax({
	             type: "POST",
	             url: "/well/json/create-comment",
	             success: function(result) {
		             console.log(result);
	                 if (result.code == 200) {
	                	 $("#commentTextFld").val('');
	                	 $('#commentPrivateChk').prop('checked', false);
	                 	$('#addComment').modal('hide');
	         	    	$("#alertSuccessBoxTxt").html('Your Comment was saved for this well <i class="fa  fa-comment-o fw"></i>');
	         	    	$("#alertSuccesBox").show();
	                 } else {
	                	 $("#alertErrorCommentTxt").html(result.response);
	             	     $("#alertErrorCommentBox").show();
	                 }
	             },
	             error: function (xhr, ajaxOptions, thrownError) {
	                 
	                 console.log(thrownError);
	               },
	             data: {wellId: d.id , wellCommentTxt: commentTxt, wellCommentPrivate: commentPrivate },
	             dataType: 'json',
	 	    });
	    	// reload comments
		});

	    updateModals(d);
	} else {
		$("#alertError").html(result.response);
	    $("#alertError").show();
	}
}

function updateModals(data) {
    $("#favoritesTxt").html(data.street + " " + data.city);
}

function errorFn (xhr, status, strErr) {
	$("#alertError").html("There was and Error " + strErr);
    $("#alertError").show();
	console.log("There was and Error " + strErr);
}

function loadMap(lat, lng) {
    console.log("map " + lat);
	//map
    MQA.EventUtil.observe(window, 'load', function() {

     // create an object for options
     var options = {
       elt: document.getElementById('mapContainer'),           // ID of map element on page
       zoom: 10,                                      // initial zoom level of the map
       latLng: { lat: 39.743943, lng: -105.020089 },  // center of map in latitude/longitude
       mtype: 'map',                                  // map type (map, sat, hyb); defaults to map
       bestFitMargin: 0,                              // margin offset from map viewport when applying a bestfit on shapes
       zoomOnDoubleClick: true                        // enable map to be zoomed in when double-clicking on map
     };

    //construct an instance of MQA.TileMap with the options object
     window.map = new MQA.TileMap(options);
    });
}
</script>


<div class="alert alert-danger" style="display: none;" id="alertError"></div>
<div class="alert alert-success alert-dismissible" role="alert" id="alertSuccesBox">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <strong>Success!</strong> <span id="alertSuccessBoxTxt"></span>
</div>
<?php echo $this->wellNav(); ?>
<section id="details">
    <div class="panel panel-default">
        <div class="panel-body">
        
            <section id="well">
            <div class="row">
                <section id="wellDetails">
                <div class="col-md-8">
                    <h3>Location</h3>
                    <div class="row">
                        <div class="col-md-4"><strong class="text-primary">County:</strong> <span id="wlCountyCode"></span></div>
                        <div class="col-md-4"><strong class="text-primary">State:</strong> OR</div>
                        <div class="col-md-4"><strong class="text-primary">Log Type:</strong> <span id="typeOfLog"></span></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"><strong class="text-primary">Street:</strong> <span id="wellStreet"></span></div>
                        <div class="col-md-4"><strong class="text-primary">City:</strong> <span id="wellCity"></span></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"><strong class="text-primary">State Well Record:</strong> <span id="wlNbr"></span></div>
                        <div class="col-md-4"><strong class="text-primary">Well Tag:</strong> <span id="wellTagNbr"></span></div>
                         <div class="col-md-4"><strong class="text-primary">State Card No:</strong> <span id="startcardNbr"></span></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"><strong class="text-primary">TRS:</strong> <span id="trs"></span></div>
                        <div class="col-md-4"><strong class="text-primary">LAT/LNG:</strong> <span id="latLng"></span></div>
                        <div class="col-md-4"><strong class="text-primary">Tax Lot:</strong> <span id="txLot"></span></div>
                    </div>
                    <hr />
                    <h3>Owner</h3>
                    <div class="row">
                        <div class="col-md-12"><strong class="text-primary">Name:</strong> <span id="name"></span></div>
                    </div>
                    <div class="row">
                        <div class="col-md-12"><strong class="text-primary">Company:</strong> <span id="nameCompany"></span></div>
                    </div>
                    <div class="row">
                        <div class="col-md-12"><strong class="text-primary">Address:</strong> <span id="address"></span></div>
                    </div>
                    <hr>
                    
                    <h3>Details</h3>
                    <div class="row">
                        <div class="col-md-4"><strong class="text-primary">Start Date:</strong> <span id="startDate"></span></div>
                        <div class="col-md-4"><strong class="text-primary">Completed Date:</strong> <span id="completeDate"></span></div>
                        <div class="col-md-4"><strong class="text-primary">Received Date:</strong> <span id="receivedDate"></span></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"><strong class="text-primary">First Water Depth:</strong> <span id="depthFirstWater"></span></div>
                        <div class="col-md-4"><strong class="text-primary">Depth Drilled:</strong> <span id="depthDrilled"></span></div>
                        <div class="col-md-4"><strong class="text-primary">Completed Depth:</strong> <span id="completedDepth"></span></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"><strong class="text-primary">Static Level:</strong> <span id="postStaticWaterLevel"></span></div>
                        <div class="col-md-4"><strong class="text-primary">Yield:</strong> <span id="maxYield"></span> </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-12"><strong class="text-primary">Last Work Recorded:</strong> <span id="lastWork"></span></div>
                    </div>
                    <div class="row">
                         <div class="col-md-12"><strong class="text-primary">Well Use:</strong> <span id="use"></span></div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-4"><strong class="text-primary">Driller:</strong> <span id="driller"></span></div>
                        <div class="col-md-4"><strong class="text-primary">Bonded License No:</strong> <span id="bondedLicenseNbr"></span></div>
                    </div>
                </div>
                </section>
                
                <section id="mapSection">
                <div class="col-md-4">
                    <div class="thumbnail" id="mapContainer" style="height:260px;">
                         
                    </div>
                    <hr />
                   
                        <div class="row" style="padding-bottom:8px;">
                            <div class="col-md-12">
                                 <a href="#" data-toggle="modal" data-target="#addFavorites" class="btn btn-primary btn-lg btn-block" id="addToFavortiesBtn"><i class="fa fa-star-o fa-fw"></i> Add To Favorites</a>
                            </div>
                        </div>
                        
                        <div class="row" style="padding-bottom:8px;">
                            <div class="col-md-12">
                                <a href="#" data-toggle="modal" data-target="#apiInfo" class="btn btn-primary btn-lg btn-block"><i class="fa fa-exchange fa-fw"></i> API Info</a>
                            </div>
                        </div>
                        <div class="row" style="padding-bottom:8px;">
                            <div class="col-md-12">
                                <a href="#" data-toggle="modal" data-target="#addComment" class="btn btn-primary btn-lg btn-block"><i class="fa  fa-comment-o fw"></i> Leave Comment</a>
                            </div>
                        </div>
                        <div class="row" style="padding-bottom:8px;">
                            <div class="col-md-12">
                                <a href="#" data-toggle="modal" data-target="#printReport" class="btn btn-primary btn-lg btn-block"><i class="fa fa-print fa-fw"></i> Print Report</a>
                            </div>
                        </div>
                        <div class="row" style="padding-bottom:8px;">
                            <div class="col-md-12">
                                <a href="#" id="stateReportBtn" target="new" class="btn btn-primary btn-lg btn-block"><i class="fa fa-file-pdf-o fa-fw"></i> View State Report</a>
                            </div>
                        </div>
                        <div class="row" style="padding-bottom:8px;">
                            <div class="col-md-12">
                                <a href="#" id="viewDrillerBtn" data-toggle="modal" data-target="#viewDriller" class="btn btn-primary btn-lg btn-block"><i class="fa fa-wrench fa-fw"></i> View Driller Information</a>
                            </div>
                        </div>
                       
                </div>
                </section>
            </div>
            </section>
            <hr />
            <section id="comments">
            <h3>Comments</h3>
                <div id="commentBox"></div>
            </section>
  
        </div>
    </div>  
</section>


<!-- Modals -->
<div class="modal fade" id="addFavorites" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Add To My Favorites</h4>
      </div>
      <div class="modal-body">
        <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
            <div class="alert alert-info">
               <i class="fa fa-star-o fa-fw"></i> Click save to add <span id="favoritesTxt"></span> to your favorites.
                <input type="hidden" id="" value="<?php echo $this->id; ?>">
            </div>
        <?php else:?>
            <div class="alert alert-danger">You are not signed in.</div>
            <?php echo $this->partial('login.phtml')?> 
        <?php endif;?>
      </div>
      <div class="modal-footer">
         <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
         <button id="favoritesBtn" type="button" class="btn btn-primary" <?php if ($this->GetIdentity()->auth_type == 'Guest'): ?>disabled="disabled"<?php endif;?>>Save</button>
         <?php endif;?>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
    </div>
  </div>
</div>

<!-- API -->
<div class="modal fade" id="apiInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">API Information</h4>
      </div>
      <div class="modal-body">
       <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
         
        <?php else:?>
            <div class="alert alert-danger">You are not signed in.</div>
            <?php echo $this->partial('login.phtml')?> 
        <?php endif;?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- Add Comment -->
<div class="modal fade" id="addComment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Leave A Comment</h4>
      </div>
      <div class="modal-body">
       
         <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
           <div class="alert alert-danger" id="alertErrorCommentBox"><span id="alertErrorCommentTxt"></span></div>
            <form class="form-horizontal" role="form" id="addCommentForm">
              <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Comment</label>
                <div class="col-sm-10">
                  <textarea class="form-control" rows="3" id="commentTextFld" data-bv-notempty data-bv-notempty-message="Comment is required!" ></textarea>
                </div>
              </div>
               <div class="form-group">
               <div class="checkbox">
                <div class="col-sm-10">
                      <label>
                        <input type="checkbox" value="1" id="commentPrivateChk">
                        Check this box to make private message for the admin.
                      </label>
                    </div>
                    </div>
               </div>
           </form>
          <div class="clear-fix"></div>
        <?php else:?>
            <div class="alert alert-danger">You are not signed in.</div>
            <?php echo $this->partial('login.phtml')?> 
        <?php endif;?>
      </div>
      <div class="modal-footer">
         <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
            <input type="hidden" name="from" value="/well/view/index/id/<?php echo $this->id; ?>" id="from">
         <  button id= "saveCommentBtn"type="button" class="btn btn-primary">>Save</button>
         <?php endif;?>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
      </div>
    </div>
  </div>
</div>

<!-- print Report -->
<div class="modal fade" id="printReport" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Your Report</h4>
      </div>
      <div class="modal-body">
        
        <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
         
        <?php else:?>
            <div class="alert alert-danger">You are not signed in.</div>
            <?php echo $this->partial('login.phtml')?> 
        <?php endif;?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- View Driller -->
<div class="modal fade" id="viewDriller" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Driller Information For <span id="drillerName"></span></h4>
      </div>
      <div class="modal-body">
        
        <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
         
        <?php else:?>
        <div class="alert alert-danger">You are not signed in.</div>
        <?php echo $this->partial('login.phtml')?> 
        </form>
        <?php endif;?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- Delete Comment -->
<div class="modal fade" id="deleteComment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Delete Comment</h4>
      </div>
      <div class="modal-body">
        <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
            <div class="alert alert-danger" role="alert" id="deleteCommentAlert">You are not signed in.</div>
            <div class="alert alert-success" role="alert" id="deleteCommentSuccess"></div>
            <div class="alert alert-info" id="deleteCommentInfo">
                Are You sure you want to delete the comment?<br />
                <span id="deleteCommentTxt"></span>
                <input type="hidden" id="" value="">
            </div>
        <?php else:?>
        <div class="alert alert-danger">You are not signed in.</div>
        <?php echo $this->partial('login.phtml')?> 
        <?php endif;?>
       
      </div>
      <div class="modal-footer">
         <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
            <button class="btn btn-primary" id="doDeleteCommentBtn">Delete Comment</button>
        <?php endif;?>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
  </div>
</div>

<!-- Edit Comment -->
<div class="modal fade" id="editComment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Comment</h4>
      </div>
      <div class="modal-body">
        <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
            <div class="alert alert-danger" role="alert" id="editCommentAlert">You are not signed in.</div>
            <div class="alert alert-success" role="alert" id="editCommentSuccess"></div>
            <form class="form-horizontal" role="form" id="addCommentForm">
              <div class="form-group" id="editCommentFormGroup">
                <label for="inputEmail3" class="col-sm-2 control-label">Comment</label>
                <div class="col-sm-10">
                  <textarea class="form-control" rows="3" id="commentEditTextFld" data-bv-notempty data-bv-notempty-message="Comment is required!" ></textarea>
                </div>
              </div>
              
           </form>
          <div class="clear-fix"></div>
        <?php else:?>
           <div class="alert alert-danger">You are not signed in.</div>
           <?php echo $this->partial('login.phtml')?> 
        <?php endif;?>
      </div>
      <div class="modal-footer">
         <?php if ($this->GetIdentity()->auth_type != 'Guest'): ?>
        <button class="btn btn-primary" id="doEditCommentBtn">Save Comment</button>
        <?php endif;?>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
  </div>
</div>

<div class="modal fade" id="helpBrowse" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Help</h4>
      </div>
      <div class="modal-body">
         
       
      </div>
      <div class="modal-footer">
        
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
  </div>
</div>