<div class="row">
    <div class="col-md-6 col-lg-6">
        <div class="well">
            <?php echo $this->form; ?>
        </div>
    </div>
    <div class="col-md-6 col-lg-6">
        <img src="/images/it-security-content-filtering.png" alt="No Contracts" class="pull-left" />
			<p>
			An advantage to signing up for our "Managed Services" plans is giving our customer's 
			exclusive access to check the progress and status of their open Service Requests. 
			In addition, Our Clients can also access all their ticket history and our internal 
			knowledge base and self help tools.</p>
			
			<p>Need instant computer support? With our Remote IT Support capabilities, we can connect 
			securely to your system and begin troubleshooting your issues within seconds. We have a 
			"No Resolution, No Pay" policy. Call us today <strong class="text-primary">541-2954642</strong> or send us a service request</p>
    
        
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-pills">
          <li class="active"><a href=""><?php echo $this->translate('Lost Password')?></a></li>
          <li class="active"><a href=""><?php echo $this->translate('Register')?></a></li>
        </ul>
        
    </div>
</div>
