<form role="form" class="form-horizontal" action="/auth/signin/index"
	method="post">
	<div class="form-group">
		<label for="inputEmail3" class="col-sm-2 control-label">Email</label>
		<div class="col-sm-10">
			<input type="email" class="form-control" id="username"
				name="username" placeholder="Email">
		</div>
	</div>
	<div class="form-group">
		<label for="inputPassword3" class="col-sm-2 control-label">Password</label>
		<div class="col-sm-10">
			<input type="password" class="form-control" id="password"
				name="password" placeholder="Password">
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<input type="hidden" name="from"
				value="/well/view/index/id/<?php echo $this->id; ?>" id="from">
			<button class="btn btn-primary">Sign in</button>
			<button class="btn btn-primary">Create Account</button>
		</div>
	</div>
</form>