<div class="row">
	<div class="col-md-3 col-lg-4">
        <?php echo $this->Nav(); ?>
    </div>
	<div class="col-md-9 col-lg-8">
	   <table class="table table-striped table-bordered table-responsive">
			<thead>
				<tr>
				    <th><?php echo $this->translate('Cache Directory')?>
				    <th class="col-md-2"></th>
				</tr>
		    </thead>
		    <tbody>
		    <?php 
		    if ($this->handle = opendir(APPLICATION_PATH . '/cache')) {
		        while (false !== ($entry = readdir($this->handle))) {
		            if ($entry != "." && $entry != "..") {
		                echo '
	                    <tr>
	                       <td>'. $entry .'</td>
	                       <td class="text-right">';
				           echo $this->DeleteButton('/cache/index/clean/directory/' .$entry, 'Clean Cache Directory ' .  $entry);
				        echo '</td>
	                    </tr>
	                   ';
		            }
		        }
		        closedir($this->handle);
		    }
		    
		    ?>
		    </tbody>
	   </table>
	</div>
</div>