<div class="row">
	<div class="col-md-3 col-lg-4">
        <?php echo $this->Nav(); ?>
    </div>
	<div class="col-md-9 col-lg-8">
	   <table class="table table-striped table-bordered table-responsive small">
			<thead>
				<tr>
				    
				    <th>Label</th>
				    <th>Module</th>
				    <th>Controller</th>
				    <th>Action</th>
				    <th>Access</th>
				    <th>Visible</th>
				    <th>Reset Params</th>
				    <th class="col-md-3"></th>
				    
				</tr>
		    </thead>
		    <tbody>
		    <?php foreach($this->navigations as $navigation):?>
		    <tr>
		      <td>
		          <a href="/navigation/index/index/parent_id/<?php echo $navigation->navigation_id?>"><?php echo $navigation->label?></a>
		      </td>
		      <td><?php echo $navigation->module ?></td>
		      <td><?php echo $navigation->controller ?></td>
		      <td><?php echo $navigation->action ?></td>
		      <td><?php echo $navigation->acl_resource_display ?></td>
		      <td><?php echo $navigation->visible ?></td>
		      <td><?php echo $navigation->reset_params ?></td>
		      <td class="text-right">
		           <?php echo $this->CreateButton('/navigation/index/create/parent_id/', $this->translate('Create Navigation'));?>
	               <?php echo $this->UpdateButton('/navigation/index/update/navigation_id/', $this->translate('Update Navigation'))?>
	               <?php echo $this->DeleteButton('/navigation/index/delete/navigation_id/', $this->translate('Delete Navigation'))?>
	       
		      </td>
		    </tr>
		    <?php endforeach;?>
		    </tbody>
	   </table>
	</div>
</div>