<script type="text/javascript">
$(document).ready(function() {
    $('#attributeForm').bootstrapValidator();
});
</script>
<div class="panel panel-default">
  <div class="panel-body">
   

  <form id="attributeForm" method="post" class="form-horizontal"
    data-bv-message="This value is not valid"
    data-bv-feedbackicons-valid="glyphicon glyphicon-ok"
    data-bv-feedbackicons-invalid="glyphicon glyphicon-remove"
    data-bv-feedbackicons-validating="glyphicon glyphicon-refresh">
    
    <div class="form-group">
        <label class="col-lg-3 control-label">Business name</label>
        <div class="col-lg-4">
            <input type="text" class="form-control" name="businessName" 
                data-bv-notempty="true"
                data-bv-notempty-message="The business name is required and cannot be empty" autocomplete="off"/>
        </div>
        
    </div>
    
    
    </form>
   </div>
</div>