<script type="text/javascript">
$(document).ready(function() {
    $('#attributeForm').bootstrapValidator();
});
</script>
<div class="panel panel-default">
  <div class="panel-body">
   

  <form id="attributeForm" method="post" class="form-horizontal"
    data-bv-message="This value is not valid"
    data-bv-feedbackicons-valid="glyphicon glyphicon-ok"
    data-bv-feedbackicons-invalid="glyphicon glyphicon-remove"
    data-bv-feedbackicons-validating="glyphicon glyphicon-refresh">
    
    
    </form>
   </div>
</div>