
        <?php if ($this->pageCount): ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<a href="<?php echo $this->url(array('page' => $this->previous)); ?>"
	title="Previous">Previous</span></a>
<?php else: ?>
<!--  <span class="disabled">&lt; Previous</span> |-->
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
              <?php if ($page != $this->current): ?>
<a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
<?php else: ?>
              	<?php echo $page; ?>
              <?php endif; ?>
            <?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
<a href="<?php echo $this->url(array('page' => $this->next)); ?>"
	class="button right" title="Next">Next</span></a>
<?php else: ?>
<!-- <span class="disabled">Next &gt;</span>  -->
<?php endif; ?>
            
            <?php endif; ?>
        