<html lang="en">
<head>
<meta charset="utf-8">

	 <script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
	 <script src="http://cdn.datatables.net/1.10.0/js/jquery.dataTables.js" type="text/javascript"></script>

	 
	 </head>
<body>

<script>
var p = $("p");

$("document").ready( function () {
	alert("Page loaded");
});



</script>

<ul id="list1>
	<li class="a">Item 1</li>
	<li class="a">Item 2</li>
	<li class="b">Item 3</li>
	<li class="b">Item 4</li>
	<li class="c">Item 5</li>
	
</ul>

<p>This is paragraph 1</p>
<p>This is paragraph 2</p>
<p>This is paragraph 3</p>
<p>This is paragraph 4</p>
<p>This is paragraph 5</p>
<p>This is paragraph 6</p>
</body>

</html>