<div class="jumbotron">
<h3><center>Jaimie Garner
<br /><small>Proven Success in Systems Optimization and Strategic IT Solutions</small></center></h3>
</div>

<div class="row">
	<div class="col-md-6">
		<p><strong>Accomplished network & systems administrator</strong> with 13 years of experience managing server infrastructures and business IT operations 
			across multiple platforms (Unix, Linux, Windows). Effectively plan, install, configure and optimize the IT infrastructure to consistently achieve high 
			availability and performance.
		</p>
	</div>
	<div class="col-md-6">
		<p><strong>Proven ability to create and deliver solutions tied to business growth</strong>, organizational development and systems/network optimization. 
			Skilled problem identifier and troubleshooter comfortable managing systems, projects and teams in a range of IT environments.
		</p>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		 <div class="page-header"><h3><center>Highlights of Information Technology Skills</center></h3></div>
	</div>
</div>

<div class="row">
	<div class="col-md-4">
		<ul class="list-group">
			<li class="list-group-item">Network Systems Management</li>
			<li class="list-group-item">Windows Server Administration</li>
			<li class="list-group-item">Unix/Linux Server Administration</li>
		</ul>
	</div>
	<div class="col-md-4">
		<ul class="list-group">
			<li class="list-group-item">Technical Support</li>
			<li class="list-group-item">Systems Installation, Configuration & Upgrading</li>
			<li class="list-group-item">Security Solutions </li>
		</ul>
	</div>
	<div class="col-md-4">
		<ul class="list-group">
			<li class="list-group-item">Database Design & Management</li>
			<li class="list-group-item">Programming PHP, Java, C++, C#, Dot Net</li>
			<li class="list-group-item">Training & Mentoring</li>
		</ul>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		 <div class="page-header"><h3><center>Professional Experience</center></h3></div>
	</div>
</div>

<div class="row">
	<div class="col-md-12 well">
		<h4>www.4scopes.com<small> -- Grants Pass, Oregon, 2013 to present</small></h4>
		<p><strong>System Administrator / application developer</strong> -- Contact: Joel Cannon Owner<br />
			Currently working part-time as System administrator and web developer for E-commerce business selling 
			Optics and other firearm products. Wrote several applications to mine data and collect product information from 
			product manufactures. Built custom Magento plugins. Provided Desktop support to staff. Maintained Xen Virtual Server farm. 
		</p>
	</div>
</div>

<br />

<div class="row well">
	<div class="col-md-12">
		<h4>Its-Managed / Budget Internet<small>-- Grants Pass, Oregon, 2006 to 2013</small> </h4>
		<p><strong>Senior Systems & Network Administrator</strong> -- Contact:  Josh Hatch supervisor<br />
			Wile working for Its-Managed I provided Systems Administration and IT consultation to hundreds of businesses in  the Rogue Valley. 
			I worked with a wide variety of business sectors managing everything from networking, server infrastructure, and desktop support to 
			individual business software support. While working with Budget Internet I engineered and designed Budgets core wireless network infrastructure 
			that provides ISP services to their subscribers. I also worked with Visp's software group to help improve their billing and management software. 
			Day to day tasks covered everything from simple desktop support to complete sever disaster recovery. <br />
			<strong>Key Contributions:</strong>
			<ul>
				<li>Planed, designed, managed, maintained, documented and migrated several Windows sever 2003 domains to server 2008 and 2012.</li>
				<li>Analyzed businesses IT infrastructures and designed cost effective solutions that saved money and provided more reliable networks. </li>
				<li>Researched, recommended and implemented network enhancements that improved system reliability and performance.</li>
				<li>Provided technical training to non technical staff and helped business become more efficient using their network systems.</li>
				<li>Consulted with clients on hardware, software and service purchases to find the best solutions to meet business needs and demands.</li>
				<li>Supported various client software applications and worked with vendors to resolve issues in a timely manner.</li>
				<li>Engineered and deployed microwave wireless internet services for Budget Internet. </li>
				<li>Created methods and procedures for installing customer premise equipment.</li>
				<li>Provided residential computer repair both hardware and software.</li>
			</ul>			
		</p>
	</div>
</div>
 
<br />
 
<div class="row well">
 	<div class="col-md-12">
 		<h4>Ken Roberts Company<small> -- Grants Pass, OR, 2004 to 2006</small></h4>
		<p><strong>Unix Administrator / Application Developer</strong> -- Contact: Steve O'Connor<br />
			Hired as a part-time Unix systems administrator and part-time application developer. <br />			
			<strong>Key Contributions:</strong>
			<ul>
				<li>Evaluated and reconfigured company's Unix/Linux/MySQL setup, creating web/database farm to handle large volumes of web traffic.</li>
				<li>Deployed and managed FreeBSD e-mail sever farm to deliver e-mail marketing campaigns. Managed spam policies and black listing issues.</li>
				<li>Assisted in creating MySQL database farm utilizing replication to provide n+1 data redundancy and availability.</li>
				<li>Analyzed MySQL Innodb database deadlocks and created various stored procedures and indexing to alleviate deadlocks</li>
				<li>Researched, recommended and implemented network enhancements that improved system reliability and performance using load balancing equipment.</li>
				<li>Worked with development team writing PHP/MySQL applications which managed commodities and stock trading.</li>
				<li>Trained other IT staff on managing Linux and Unix servers. Provided Desktop support to staff when needed.</li>
				
			</ul>
		</p>
 	</div>
 </div>
 
 <br />
 
 <div class="row well">
 	<div class="col-md-12">
 		<h4>Self Employed Pacific Network Management<small> -- Portland / Grants Pass 2003 to Present</small></h4>
		<p><strong>Systems Administrator Contract IT and Contract Application Development</strong><br />
		Worked as a freelance programmer on several web applications creating, modifying and maintain existing web sites. Contracted break fix desktop 
		repair through onforce.com and other sites.<br /> 
		<strong>Key Contributions:</strong>
		<ul>
		
		<li>Programmed web based applications using PHP, HTML, CSS, JavaScript and Java on a contractual basis.</li>
		<li>Utilized Object Oriented programming techniques to achieve goals in a cost effective manner</li>
		<li>Preformed desktop warranty hardware repair for Dell, HP and Compaq through Onforce.com and ComputerRepair.com</li>
		</ul>
		</p>
 	</div>
 </div>
 
 <br />
 
 <div class="row well">
 	<div class="col-md-12">
 		<h4>DirecTV Broadband Portland, OR, <small> -- 2000 to 2003</small></h4>
 		<p><strong>Technical Analyst Technical Support</strong><br /> 
		Worked as Level 1 support technician providing customer support for DSL subscribers. Advanced to level 3 support technician and 
		provided support to the technical teams and new hires. From 2002 to 2003 I provided technical analysis to engineering group on key 
		DSL install failures by reviewing thousands of failures over the course of 3 years and 350,000 subscribers. Managed and trained a new
		beta support team to provide support  for third generation DSL router<br />
		<strong>Key Contributions:</strong>
		<ul>
			<li>Provided tier 1 technical support, trouble shooting PC to Router Issues.</li>
			<li>Provided tier 2 technical support, trouble shooting LEC issues and Nortel Shasta 5000 BSN</li>
			<li>Mentored tier 1 support staff and trained new hires.</li>
			<li>Managed small team of 15 that implemented new methods and troubleshooting procedures.</li>
			<li>Created company documentation covering training methods and procedures.</li>
 		</ul>
 		</p>
 	</div>
 </div>
 
 <br />
 
 <div class="row">
	<div class="col-md-12">
		 <div class="page-header"><h3><center>Additional Information Technology Experience</center></h3></div>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<p>In 2006 I Helped Bill Collins to launch bio-plastics company Trellis Earth Products.  I Provided Trellis Earth with 
		technical consultation and Initial ecommerce web store. I Also designed and launched their first call center based on Open source solutions such as 
		Diskless Linux and Asterisk PBX system. The business still thrives today and has become a major player in the Bio-Plastics industry.  I remain a share 
		holder in the company and still provide IT consulting.</p>
	</div>
</div>

<br />

 <div class="row">
	<div class="col-md-12">
		 <div class="page-header"><h3><center>Education & Training</center></h3></div>
	</div>
</div>
 <div class="row">
	<div class="col-md-6">
		<ul class="list-group">
			<li class="list-group-item">Lewis Palmer High School— Co. Springs CO<br />
				High School Diploma</li>
			<li class="list-group-item">ITT Technical Institute Portland OR 2000 - 2003<br />
				AAS Network Systems Management</li>
			<li class="list-group-item">Brain Bench Skills assessment  2000<br />
				Certified Linux Administrator</li>
		</ul>
	</div>
	<div class="col-md-6">
		<ul class="list-group">
			<li class="list-group-item">Hughes Corp Portland OR 2000<br />
				Customer Service and  Care Training</li>
			<li class="list-group-item">Hughes Corp Portland OR 2001 - 2003<br /> 
				Nortel Shasta Networks BSN</li>
			<li class="list-group-item">Dell Corp  2006<br /> 
				Dell Certified Systems Expert, DCSE</li>
		</ul>
	</div>
</div>
 
 
