<div class="row">
	<div class="col-md-4">
        <?php echo $this->PageNav(); ?>
    </div>
	<div class="col-md-8">
	    <h3>Create Page Translation For</h3>
		<div class="row">
		  <div class="col-md-2 text-primary"><b>Route</b></div>
		  <div class="col-md-10"><?php echo $this->escape($this->page->route); ?></div>
		</div>
		<div class="row">
		  <div class="col-md-2 text-primary"><b>Module</b></div>
		  <div class="col-md-10"><?php echo $this->escape($this->page->module); ?></div>
		</div>
		<div class="row">
		  <div class="col-md-2 text-primary"><b>Controller</b></div>
		  <div class="col-md-10"><?php echo $this->escape($this->page->controller); ?></div>
		</div>
		<div class="row">
		  <div class="col-md-2 text-primary"><b>Action</b></div>
		  <div class="col-md-10"><?php echo $this->escape($this->page->action); ?></div>
		</div>
		<div class="row">
		  <div class="col-md-2 text-primary"><b>Access</b></div>
		  <div class="col-md-10"><?php echo $this->escape($this->page->acl_resource_display); ?></div>
		</div>
		<hr />
		<?php echo $this->form; ?>
	</div>
</div>