<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">    
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/dist/css/bootstrapValidator.min.css"/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
   
   <link rel="stylesheet" href="/dist/css/jquery-ui-1.10.0.custom.css"/>
   
    <script src="//code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.js"></script>
    <script src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="/dist/js/bootstrapValidator.js" type="text/javascript"></script>   
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="/dist/js/jquery.ui.map.full.min.js" type="text/javascript" ></script>
    <script type='text/javascript' src='https://www.google.com/jsapi'></script>
    <script type='text/javascript' src='/dist/js/jquery-ui-1.10.3.js'></script>
    
    <base href="<?php echo $this->baseUrl(); ?>" />
  </head>
  <body id="top" >
  
    <div id="wrap">
      <div class="container">
        <?php if ($this->appConfig->installed == 'true'): ?>  	       
          <?php echo $this->render('horizontal.phtml') ?>
        <?php endif; ?>
        <div class="page-header">
          <h3><?php echo $this->pageTitle; ?></h3>
        </div>
         
        <?php if ($this->appConfig->installed == 'true'): ?>
          <div id="flashMessenger">
            <?php echo $this->FlashMessenger(); ?>
          </div>
        <?php endif; ?>
        <?php echo $this->layout()->content; ?>		
      </div>
    </div>
    <div id="footer">
      <div style="background-color: #858585; padding-top: 6px; color: #FFFFFF">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <p class="pull-left">&copy; 2012 - <?php echo date("Y") ?> Pacific Network Management, LLC.
                All Rights Reserved</p>
              <p class="pull-right">Powered by the PNM framework 1.0</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>