<script type="text/javascript">

$(document).ready(function() {
    var table = $('#pageTable').DataTable();
 
    $("#pageTable tfoot th").each( function ( i ) {
        var select = $('<select><option value=""></option></select>')
            .appendTo( $(this).empty() )
            .on( 'change', function () {
                table.column( i )
                    .search( '^'+$(this).val()+'$', true, false )
                    .draw();
            } );
 
        table.column( i ).data().unique().sort().each( function ( d, j ) {
            select.append( '<option value="'+d+'">'+d+'</option>' )
        } );
    } );
} );

</script>

<div class="row">
	<div class="col-md-3">
        <?php echo $this->PageNav(); ?>
    </div>
	<div class="col-md-9">
	<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Pages</h3>
			</div>
	   <div class="table-responsive">
		<table class="table table-striped table-bordered small" id="pageTable">
			<thead>
				<tr>
					<th>Route</th>
					<th>Module</th>
					<th>Controller</th>
					<th>Action</th>
					<th></th>
				</tr>
			</thead>
			<tfoot>
			 <tr>
			     <th>Route</th>
					<th>Module</th>
					<th>Controller</th>
					<th>Action</th>
					<td></td>
			 </tr>
			</tfoot>
			<tbody>
			<?php foreach($this->pages as $page):?>
			<tr>
					<td><a
						href="<?php echo $this->url( array(
						        'module' => 'page', 
						        'controller' => 
						        'view', 
						        'action' => 
						        'index', 
						        'page_id' => $this->escape($page->page_id) ));?>">
						<?php echo $this->escape($page->route); ?></a></td>
					<td><?php echo $this->escape($page->module); ?></td>
					<td><?php echo $this->escape($page->controller); ?></td>
					<td><?php echo $this->escape($page->action); ?></td>
					<td class="text-right">
					   <a href="<?php echo $this->url(
		              array('module' => 'page', 
                            'controller' => 'update', 
                            'action' => 'page', 
                            'page_id' => $this->escape($page->page_id)) ); ?>" 
                        type="button" class="btn btn-warning btn-xs" data-toggle="tooltip" 
                        data-placement="top" title="Update Page"><i class="glyphicon glyphicon-pencil"></i></a>
                      <a href="<?php echo $this->url( array('module' => 'page',
                            'controller' => 'delete', 'action' => 'page', 'page_id' => $this->escape($page->page_id)) ); ?>" type="button" class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" title="Delete Page"><i class="glyphicon glyphicon-remove"></i></a>
                           
					</td>
				</tr>
			<?php endforeach;?>
			</tbody>
			
		</table>
		</div>
		</div>
	</div>
</div>