<div class="row">
	<div class="col-md-3">
        <?php echo $this->AuthNav(); ?>
    </div>
	<div class="col-md-9">
		<table class="table table-striped table-bordered table-responsive">
			<thead>
				<tr>
				    <th>Id</th>
				    <th>Username</th>
				    <th>Email</th>
				    <th>Name</th>
				    <th>Role</th>
				    <th></th>
				</tr>
		  </thead>
		  <tbody>
		      <?php foreach ($this->accounts as $account):?>
		      <tr>
		          <td><?php echo $account->auth_id; ?></td>
		          <td><a href="<?php echo $this->url(array('module' => 'auth', 'controller' => 'admin', 'action' => 'view', 'auth_id' => $account->auth_id)); ?>"><?php echo $account->username; ?></a></td>
		          <td><?php echo $account->email; ?></td>
		          <td><?php echo $account->name; ?></td>
		          <td><?php echo $account->acl_role_display; ?></td>
		          <td class="text-right">
		              <a href="<?php echo $this->url(array('module' => 'auth', 'controller' => 'admin', 'action' => 'update', 'auth_id' => $account->auth_id)); ?>" type="button" class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Update Account"><i class="glyphicon glyphicon-pencil"></i></a>
                      <a href="<?php echo $this->url(array('module' => 'auth', 'controller' => 'admin', 'action' => 'delete', 'auth_id' => $account->auth_id)); ?>" type="button" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Delete Account"><i class="glyphicon glyphicon-remove"></i></a>
		          </td>
		      </tr>
		      <?php endforeach;?>
		  </tbody>
	   </table>
	
	</div>
</div>